# Agua y riego
AGUA_INICIAL_PLANTACION = 500.0
TEMP_MIN_RIEGO = 8
TEMP_MAX_RIEGO = 15
HUMEDAD_MAX_RIEGO = 50

# Sensores (segundos)
INTERVALO_SENSOR_TEMPERATURA = 2.0
INTERVALO_SENSOR_HUMEDAD = 3.0
INTERVALO_CONTROL_RIEGO = 2.5
THREAD_JOIN_TIMEOUT = 2.0

# Rango sensores
SENSOR_TEMP_MIN = -25
SENSOR_TEMP_MAX = 50
SENSOR_HUMEDAD_MIN = 0
SENSOR_HUMEDAD_MAX = 100

# Superficies y agua inicial por cultivo
SUPERFICIE_PINO = 2.0
AGUA_INICIAL_PINO = 2.0
ALTURA_INICIAL_PINO = 1.0

SUPERFICIE_OLIVO = 3.0
AGUA_INICIAL_OLIVO = 5.0
ALTURA_INICIAL_OLIVO = 0.5

SUPERFICIE_LECHUGA = 0.10
AGUA_INICIAL_LECHUGA = 1.0

SUPERFICIE_ZANAHORIA = 0.15
AGUA_INICIAL_ZANAHORIA = 0.0

# Persistencia
DIRECTORIO_DATA = "data"
EXTENSION_DATA = ".dat"

# Estacionalidad ejemplo
MES_INICIO_VERANO = 3
MES_FIN_VERANO = 8
ABSORCION_SEASONAL_VERANO = 5
ABSORCION_SEASONAL_INVIERNO = 2
